import { Categoria, Medida, Producto, PlantillaMensaje, Usuario } from './types';
import { calcularCostoTotal } from './utils';

// 15 CATEGORÍAS INICIALES (10 ocasiones + 5 tipos)
export const CATEGORIAS_INICIALES: Categoria[] = [
  { id: 'cat_bodas', nombre: 'Bodas', tipo: 'Ocasión', activa: true, orden: 1 },
  { id: 'cat_xvanos', nombre: 'XV Años', tipo: 'Ocasión', activa: true, orden: 2 },
  { id: 'cat_bautizos', nombre: 'Bautizos', tipo: 'Ocasión', activa: true, orden: 3 },
  { id: 'cat_graduaciones', nombre: 'Graduaciones', tipo: 'Ocasión', activa: true, orden: 4 },
  { id: 'cat_dianino', nombre: 'Día del Niño', tipo: 'Ocasión', activa: true, orden: 5 },
  { id: 'cat_diamadres', nombre: 'Día de las Madres', tipo: 'Ocasión', activa: true, orden: 6 },
  { id: 'cat_sanvalentin', nombre: 'San Valentín', tipo: 'Ocasión', activa: true, orden: 7 },
  { id: 'cat_halloween', nombre: 'Halloween', tipo: 'Ocasión', activa: true, orden: 8 },
  { id: 'cat_navidad', nombre: 'Navidad', tipo: 'Ocasión', activa: true, orden: 9 },
  { id: 'cat_anonuevo', nombre: 'Año Nuevo', tipo: 'Ocasión', activa: true, orden: 10 },
  { id: 'cat_servilletero', nombre: 'Servilletero', tipo: 'Tipo de Producto', activa: true, orden: 11 },
  { id: 'cat_charola', nombre: 'Charola', tipo: 'Tipo de Producto', activa: true, orden: 12 },
  { id: 'cat_rompecabezas', nombre: 'Rompecabezas', tipo: 'Tipo de Producto', activa: true, orden: 13 },
  { id: 'cat_portaretrato', nombre: 'Porta-retrato', tipo: 'Tipo de Producto', activa: true, orden: 14 },
  { id: 'cat_caketopper', nombre: 'Cake Topper', tipo: 'Tipo de Producto', activa: true, orden: 15 }
];

// 8 MEDIDAS ESTÁNDAR INICIALES
export const MEDIDAS_INICIALES: Medida[] = [
  { id: 'med_serv_est', nombre: "Servilletero Estándar", ancho: 10, alto: 7, profundidad: 0 },
  { id: 'med_serv_gde', nombre: "Servilletero Grande", ancho: 12, alto: 8, profundidad: 0 },
  { id: 'med_char_ch', nombre: "Charola Chica", ancho: 28.5, alto: 20, profundidad: 9 },
  { id: 'med_char_gd', nombre: "Charola Grande", ancho: 33, alto: 24, profundidad: 9 },
  { id: 'med_romp_inf', nombre: "Rompecabezas Infantil", ancho: 12, alto: 12, profundidad: 0 },
  { id: 'med_port_inf', nombre: "Porta-retrato Infantil", ancho: 12, alto: 12, profundidad: 0 },
  { id: 'med_cake_est', nombre: "Cake Topper Estándar", ancho: 15, alto: 20, profundidad: 0 },
  { id: 'med_cake_prem', nombre: "Cake Topper Premium", ancho: 20, alto: 25, profundidad: 0 }
];

// 7 PLANTILLAS DE MENSAJE INICIALES
export const PLANTILLAS_INICIALES: PlantillaMensaje[] = [
  {
    id: 'temp_contacto',
    nombre: 'Primer Contacto',
    tipo: 'Contacto',
    contenido: 'Hola {{cliente}}, gracias por comunicarte con Forja Laser. 🔨 Te ofrecemos productos personalizados en MDF de alta calidad para tus eventos. Cuéntanos, ¿qué producto te interesa o qué fecha tienes programada?',
    redes: ['whatsapp', 'facebook'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_cotizacion',
    nombre: 'Cotización',
    tipo: 'Ventas',
    contenido: 'Hola {{cliente}}, aquí tienes la cotización para tu pedido de {{producto}}:\n\n• Cantidad: {{cantidad}}\n• Precio Unitario: {{precio}}\n• Total: {{total}}\n\n*Fecha estimada del evento:* {{fecha_evento}}\n*Atendido por:* {{nombre_colaborador}}\n\n¿Te gustaría confirmar tu pedido para programar el diseño?',
    redes: ['whatsapp', 'facebook'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_cierre',
    nombre: 'Cierre de Venta',
    tipo: 'Ventas',
    contenido: '¡Excelente decisión {{cliente}}! Para proceder con tu pedido, requerimos el 50% de anticipo y el resto a la entrega. El pago lo puedes realizar por transferencia o depósito. ¿Prefieres que te comparta los datos de la cuenta?',
    redes: ['whatsapp'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_seguimiento',
    nombre: 'Seguimiento',
    tipo: 'Seguimiento',
    contenido: 'Hola {{cliente}}, te escribo para dar seguimiento a tu cotización de {{producto}}. ¿Pudiste revisar la información? Recuerda que estamos con agenda para asegurar entregas a tiempo.',
    redes: ['whatsapp'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_no_responde',
    nombre: 'Cliente No Responde',
    tipo: 'Seguimiento',
    contenido: 'Hola {{cliente}}, ¿cómo estás? Te escribo para comentarte que tu cotización sigue vigente, pero cerraremos pedidos para la fecha {{fecha_evento}} muy pronto. Quedo a tus órdenes si deseas confirmar.',
    redes: ['whatsapp'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_post_venta',
    nombre: 'Post-venta',
    tipo: 'Fidelización',
    contenido: 'Hola {{cliente}}, esperamos que tus productos de Forja Laser hayan sido de tu total agrado. Tu opinión es muy importante para nosotros. ¿Nos podrías compartir qué tal te pareció nuestro servicio?',
    redes: ['whatsapp', 'facebook', 'instagram'],
    activa: true,
    contadorUso: 0
  },
  {
    id: 'temp_negociacion',
    nombre: 'Negociación de Precio',
    tipo: 'Negociación',
    contenido: 'Hola {{cliente}}, entiendo tu presupuesto. En la compra de más de {{cantidad}} piezas te podemos respetar nuestro precio especial de mayoreo de {{precio}} por pieza, quedando un total de {{total}}. ¿Te convendría esta opción?',
    redes: ['whatsapp'],
    activa: true,
    contadorUso: 0
  }
];

// 9 PRODUCTOS INICIALES DE FORJA LASER
const now = new Date().toISOString();

const p1_cost = calcularCostoTotal(10, 7, 0, 15, false);
const p2_cost = calcularCostoTotal(10, 7, 0, 15, false);
const p3_cost = calcularCostoTotal(10, 7, 0, 15, false);
const p4_cost = calcularCostoTotal(28.5, 20, 9, 180, true, 5);
const p5_cost = calcularCostoTotal(33, 24, 9, 180, true, 5);
const p6_cost = calcularCostoTotal(12, 12, 0, 20, false);
const p7_cost = calcularCostoTotal(12, 12, 0, 20, false);
const p8_cost = calcularCostoTotal(15, 20, 0, 30, false);
const p9_cost = calcularCostoTotal(20, 25, 0, 45, false);

export const PRODUCTOS_INICIALES: Producto[] = [
  {
    id: 'prod_serv_boda',
    nombre: 'Servilletero Boda',
    categoria: 'Bodas',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Servilletero Estándar',
    medidaAncho: 10,
    medidaAlto: 7,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 15,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((70/1600)*15),
    costoMaquina: 15 * 0.15,
    costoTotal: p1_cost,
    precioMenudeo: 30,
    precioMayoreo: 25,
    cantidadMayoreo: 12,
    descripcion: 'Elegante servilletero calado en MDF de 3mm con diseño de novios, ideal para adornar mesas en tu boda o regalar como recuerdo.',
    tags: ['boda', 'servilletero', 'mdf', 'recuerdo'],
    destacado: true,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 30 - p1_cost,
    margenPorcentaje: Math.round(((30 - p1_cost) / 30) * 100 * 100) / 100
  },
  {
    id: 'prod_serv_bautizo',
    nombre: 'Servilletero Bautizo',
    categoria: 'Bautizos',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Servilletero Estándar',
    medidaAncho: 10,
    medidaAlto: 7,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 15,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((70/1600)*15),
    costoMaquina: 15 * 0.15,
    costoTotal: p2_cost,
    precioMenudeo: 30,
    precioMayoreo: 25,
    cantidadMayoreo: 12,
    descripcion: 'Servilletero con diseño de angelito calado en MDF de 3mm, ideal para recuerdos de bautizo o presentación de tres años.',
    tags: ['bautizo', 'servilletero', 'mdf', 'angelito'],
    destacado: false,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 30 - p2_cost,
    margenPorcentaje: Math.round(((30 - p2_cost) / 30) * 100 * 100) / 100
  },
  {
    id: 'prod_serv_xv',
    nombre: 'Servilletero XV Años',
    categoria: 'XV Años',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Servilletero Estándar',
    medidaAncho: 10,
    medidaAlto: 7,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 15,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((70/1600)*15),
    costoMaquina: 15 * 0.15,
    costoTotal: p3_cost,
    precioMenudeo: 30,
    precioMayoreo: 25,
    cantidadMayoreo: 12,
    descripcion: 'Servilletero de silueta de quinceañera en MDF de 3mm, cortado con alta precisión. Un recuerdo útil y duradero.',
    tags: ['xv años', 'servilletero', 'recuerdo', 'silueta'],
    destacado: false,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 30 - p3_cost,
    margenPorcentaje: Math.round(((30 - p3_cost) / 30) * 100 * 100) / 100
  },
  {
    id: 'prod_char_grad_ch',
    nombre: 'Charola de Graduación Chica',
    categoria: 'Graduaciones',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Charola Chica',
    medidaAncho: 28.5,
    medidaAlto: 20,
    medidaProfundidad: 9,
    tiempoCorteMinutos: 180,
    ensambleHabilitado: true,
    costoEnsamble: 5,
    costoMaterial: Math.ceil((1443/1600)*15),
    costoMaquina: 180 * 0.15,
    costoTotal: p4_cost,
    precioMenudeo: 80,
    precioMayoreo: 70,
    cantidadMayoreo: 6,
    descripcion: 'Charola para botana, pan o arreglos de graduación, armada en MDF de alta resistencia. Grabado con motivo de birrete.',
    tags: ['graduacion', 'charola', 'mdf', 'snack'],
    destacado: true,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 80 - p4_cost,
    margenPorcentaje: Math.round(((80 - p4_cost) / 80) * 100 * 100) / 100
  },
  {
    id: 'prod_char_grad_gd',
    nombre: 'Charola de Graduación Grande',
    categoria: 'Graduaciones',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Charola Grande',
    medidaAncho: 33,
    medidaAlto: 24,
    medidaProfundidad: 9,
    tiempoCorteMinutos: 180,
    ensambleHabilitado: true,
    costoEnsamble: 5,
    costoMaterial: Math.ceil((1818/1600)*15),
    costoMaquina: 180 * 0.15,
    costoTotal: p5_cost,
    precioMenudeo: 130,
    precioMayoreo: 115,
    cantidadMayoreo: 6,
    descripcion: 'Charola espaciosa para arreglos premium o mesa de dulces en graduación escolar. Incluye ensamble artesanal ultra-reforzado.',
    tags: ['graduacion', 'charola', 'premium', 'mesa dulces'],
    destacado: true,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 130 - p5_cost,
    margenPorcentaje: Math.round(((130 - p5_cost) / 130) * 100 * 100) / 100
  },
  {
    id: 'prod_romp_inf',
    nombre: 'Rompecabezas Infantil',
    categoria: 'Día del Niño',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Rompecabezas Infantil',
    medidaAncho: 12,
    medidaAlto: 12,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 20,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((144/1600)*15),
    costoMaquina: 20 * 0.15,
    costoTotal: p6_cost,
    precioMenudeo: 30,
    precioMayoreo: 25,
    cantidadMayoreo: 6,
    descripcion: 'Divertido rompecabezas didáctico infantil de piezas gruesas en MDF, grabado con figuras de animales para pintar o armar.',
    tags: ['didactico', 'rompecabezas', 'infantil', 'niño', 'juguete'],
    destacado: false,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 30 - p6_cost,
    margenPorcentaje: Math.round(((30 - p6_cost) / 30) * 100 * 100) / 100
  },
  {
    id: 'prod_port_inf',
    nombre: 'Porta-retrato Infantil',
    categoria: 'Día del Niño',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Porta-retrato Infantil',
    medidaAncho: 12,
    medidaAlto: 12,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 20,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((144/1600)*15),
    costoMaquina: 20 * 0.15,
    costoTotal: p7_cost,
    precioMenudeo: 30,
    precioMayoreo: 25,
    cantidadMayoreo: 6,
    descripcion: 'Porta-retrato en MDF de 3mm con soporte trasero para mesa. Ideal para fotos de 10x10 cm, ideal para decorar recámaras infantiles.',
    tags: ['didactico', 'infantil', 'portaretrato', 'fotos'],
    destacado: false,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 30 - p7_cost,
    margenPorcentaje: Math.round(((30 - p7_cost) / 30) * 100 * 100) / 100
  },
  {
    id: 'prod_cake_est',
    nombre: 'Cake Topper Estándar',
    categoria: 'Cake Topper',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Cake Topper Estándar',
    medidaAncho: 15,
    medidaAlto: 20,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 30,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((300/1600)*15),
    costoMaquina: 30 * 0.15,
    costoTotal: p8_cost,
    precioMenudeo: 80,
    precioMayoreo: 70,
    cantidadMayoreo: 3,
    descripcion: 'Adorno superior para pasteles de cumpleaños o aniversarios con la frase "Feliz Cumpleaños" calada de forma impecable en MDF.',
    tags: ['fiesta', 'pasteles', 'cumpleaños', 'caketopper'],
    destacado: false,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 80 - p8_cost,
    margenPorcentaje: Math.round(((80 - p8_cost) / 80) * 100 * 100) / 100
  },
  {
    id: 'prod_cake_prem',
    nombre: 'Cake Topper Personalizado',
    categoria: 'Cake Topper',
    tipo: 'Tipo de Producto',
    medidaNombre: 'Cake Topper Premium',
    medidaAncho: 20,
    medidaAlto: 25,
    medidaProfundidad: 0,
    tiempoCorteMinutos: 45,
    ensambleHabilitado: false,
    costoEnsamble: 0,
    costoMaterial: Math.ceil((500/1600)*15),
    costoMaquina: 45 * 0.15,
    costoTotal: p9_cost,
    precioMenudeo: 100,
    precioMayoreo: 90,
    cantidadMayoreo: 3,
    descripcion: 'Cake topper personalizado con nombre de festejado y edad. Corte súper fino calado en MDF de 3mm premium.',
    tags: ['fiesta', 'pasteles', 'personalizado', 'caketopper'],
    destacado: true,
    activo: true,
    fechaCreacion: now,
    fechaActualizacion: now,
    gananciaUnitaria: 100 - p9_cost,
    margenPorcentaje: Math.round(((100 - p9_cost) / 100) * 100 * 100) / 100
  }
];
